metal:
  children:
    masters:
      hosts:
        charmander:
          {
            ansible_host: 10.0.50.121,
            mac: "00:23:24:b0:ff:03",
            disk: sda,
            network_interface: eno1,
          }
        squirtle:
          {
            ansible_host: 10.0.50.122,
            mac: "00:23:24:e2:1f:a1",
            disk: sda,
            network_interface: eno1,
          }
        bulbasaur:
          {
            ansible_host: 10.0.50.123,
            mac: "00:23:24:e2:0d:ea",
            disk: sda,
            network_interface: eno1,
          }
    workers:
      hosts:
        pikachu:
          {
            ansible_host: 10.0.50.124,
            mac: "e0:4f:43:24:0b:53",
            disk: sda,
            network_interface: eno1,
          }
